org.gradle.daemon=false
org.gradle.jvmargs=-Xms512M -Xmx1G -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
org.gradle.configureondemand=false
enableGraalNative=false
graalHelperVersion=2.0.1
gdxVersion=1.14.2
gdxControllersVersion=2.2.4
androidPluginVersion=8.13.2
androidCompileSdk=36
androidTargetSdk=36
androidMinSdk=21
androidBuildToolsVersion=36.0.0
androidVersionCode=1
projectVersion=1.0.0
android.useAndroidX=true
android.nonTransitiveRClass=true
